function hvac_pid_nn_control_demo
% HVAC control teaching demo with thermostat and PID comparison.
% The app lets users define an outdoor temperature profile, then compares
% a basic hysteresis thermostat against a cooling-only PID controller on
% the same room model.
%
% High-level workflow:
% 1. Load a built-in ambient profile or click points to create one.
% 2. Set thermostat, room-model, and PID parameters.
% 3. Simulate both controllers over the same 24-hour window.
% 4. Compare temperatures, controller effort, and summary metrics.

state = struct();
state.timeHours = 0:(1 / 12):24;  % 5-minute step over one day.
state.profilePoints = zeros(0, 2);
state.profileSource = "manual";
state.currentProfileName = "Custom";
state.lastResults = [];
state.isSelecting = false;
state.exampleLibrary = getExampleLibrary();
state.colors = getPlotColors();

buildUi();
loadExampleProfile(1);
setStatus("idle");
logMessage("App ready. Load an example or enable Select Points to sketch a custom ambient profile.");

    function buildUi()
        figColor = [0.95 0.96 0.98];
        panelColor = [0.92 0.93 0.96];

        state.fig = figure( ...
            "Name", "HVAC PID / Neural Network Control Demo", ...
            "NumberTitle", "off", ...
            "Color", figColor, ...
            "MenuBar", "none", ...
            "ToolBar", "none", ...
            "DefaultUicontrolForegroundColor", [0 0 0], ...
            "DefaultAxesXColor", [0 0 0], ...
            "DefaultAxesYColor", [0 0 0], ...
            "DefaultTextColor", [0 0 0], ...
            "Position", [60 60 1480 820], ...
            "WindowButtonDownFcn", @onFigureClick, ...
            "CloseRequestFcn", @onCloseFigure);

        state.controlsPanel = uipanel( ...
            "Parent", state.fig, ...
            "Title", "Controls", ...
            "FontSize", 11, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "Position", [0.015 0.03 0.24 0.94]);

        state.ambientAxes = axes( ...
            "Parent", state.fig, ...
            "Units", "normalized", ...
            "Position", [0.29 0.11 0.29 0.81], ...
            "Box", "on");
        title(state.ambientAxes, "Ambient Temperature Profile");
        xlabel(state.ambientAxes, "Time (hours)");
        ylabel(state.ambientAxes, "Ambient Temperature (degF)");
        grid(state.ambientAxes, "on");
        styleAxes(state.ambientAxes);

        state.resultsAxes = axes( ...
            "Parent", state.fig, ...
            "Units", "normalized", ...
            "Position", [0.63 0.11 0.33 0.81], ...
            "Box", "on");
        title(state.resultsAxes, "Controller Comparison");
        xlabel(state.resultsAxes, "Time (hours)");
        ylabel(state.resultsAxes, "Temperature (degF)");
        grid(state.resultsAxes, "on");
        styleAxes(state.resultsAxes);

        y = 0.93;
        dy = 0.041;
        editHeight = 0.036;
        labelHeight = 0.024;
        leftX = 0.05;
        editX = 0.62;
        editW = 0.27;

        state.controls.exampleMenu = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "popupmenu", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.58 editHeight], ...
            "String", {state.exampleLibrary.name}, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", "Select a built-in ambient temperature profile.");

        state.controls.loadExampleButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.66 y 0.22 editHeight], ...
            "String", "Load", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Load the selected example profile into the ambient plot.", ...
            "Callback", @onLoadExample);
        y = y - (dy + 0.006);

        state.controls.selectButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "togglebutton", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.34 editHeight], ...
            "String", "Select Points", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Enable point-selection mode, then click in the ambient axes to create a custom profile.", ...
            "Callback", @onSelectModeChanged);

        state.controls.undoButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.42 y 0.19 editHeight], ...
            "String", "Undo", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Remove the most recently stored profile point.", ...
            "Callback", @onUndoPoint);

        state.controls.clearButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.64 y 0.20 editHeight], ...
            "String", "Clear", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Clear the ambient profile and the current simulation results.", ...
            "Callback", @onClearProfile);
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.84 0.045], ...
            "String", "Room Model", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);
        y = y - 0.055;

        state.controls.initialIndoor = createLabeledEdit( ...
            "Initial Indoor (degF)", "76", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Indoor temperature at the beginning of the simulation.");
        y = y - (dy + 0.004);

        state.controls.roomRate = createLabeledEdit( ...
            "Room Response (1/hr)", "0.20", y, leftX, editX, editW, labelHeight, editHeight, ...
            "How strongly the room temperature drifts toward the ambient temperature.");
        y = y - (dy + 0.004);

        state.controls.coolingStrength = createLabeledEdit( ...
            "AC Cooling (degF/hr)", "4.0", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Maximum cooling power applied when the controller command is 1.");
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.50 0.045], ...
            "String", "Basic Thermostat", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.thermostatEnabled = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.58 y 0.30 0.04], ...
            "String", "Enable", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Enable or disable the basic thermostat controller.");
        y = y - 0.055;

        state.controls.setpoint = createLabeledEdit( ...
            "Setpoint (degF)", "74", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Shared target temperature used by both controllers.");
        y = y - (dy + 0.004);

        state.controls.deadband = createLabeledEdit( ...
            "Deadband (degF)", "3.0", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Thermostat hysteresis width. Larger values reduce switching chatter.");
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.50 0.045], ...
            "String", "PID Controls", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidEnabled = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.58 y 0.30 0.04], ...
            "String", "Enable", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Enable or disable the PID controller.");
        y = y - 0.055;

        state.controls.pidKp = createLabeledEdit( ...
            "Kp", "0.55", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Proportional gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        state.controls.pidKi = createLabeledEdit( ...
            "Ki", "0.10", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Integral gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        state.controls.pidKd = createLabeledEdit( ...
            "Kd", "0.02", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Derivative gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [leftX y + 0.010 0.52 labelHeight], ...
            "String", "PID Mode", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidMode = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "popupmenu", ...
            "Units", "normalized", ...
            "Position", [editX y editW editHeight], ...
            "String", {"Duty Cycle", "Two Stage"}, ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", "Choose continuous PWM-like cooling or two-stage cooling.");
        y = y - 0.060;

        state.controls.simulateButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.36 0.05], ...
            "String", "Run Simulation", ...
            "FontWeight", "bold", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Run both controllers on the current ambient profile.", ...
            "Callback", @onRunSimulation);

        state.controls.animateCheckbox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.45 y 0.42 0.05], ...
            "String", "Animate Plot", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Animate the right-side comparison plot over 3 seconds after each simulation.");

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.165 0.84 0.028], ...
            "String", "Run Statistics", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.thermostatStatsBox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.070 0.39 0.085], ...
            "String", getEmptyThermostatStatsText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.5, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidStatsBox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.49 0.070 0.39 0.085], ...
            "String", getEmptyPidStatsText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.5, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.statusLabel = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.015 0.85 0.025], ...
            "String", "Status: idle", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.footerLabel = uicontrol( ...
            "Parent", state.fig, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.70 0.01 0.27 0.025], ...
            "String", "Prof. Jon Komperda, University of Illinois Chicago, 2026", ...
            "HorizontalAlignment", "right", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", figColor);

        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
    end

    function editHandle = createLabeledEdit(labelText, defaultValue, yPos, lx, ex, ew, lh, eh, tooltipText)
        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [lx yPos + 0.010 0.52 lh], ...
            "String", labelText, ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", get(state.controlsPanel, "BackgroundColor"));

        editHandle = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "edit", ...
            "Units", "normalized", ...
            "Position", [ex yPos ew eh], ...
            "String", defaultValue, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", tooltipText);
    end

    function onLoadExample(~, ~)
        loadExampleProfile(get(state.controls.exampleMenu, "Value"));
    end

    function loadExampleProfile(exampleIndex)
        exampleProfile = state.exampleLibrary(exampleIndex);
        state.profilePoints = exampleProfile.points;
        state.profileSource = "example";
        state.currentProfileName = exampleProfile.name;
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("loaded example");
        logMessage(sprintf("Loaded ambient profile: %s.", exampleProfile.name));
    end

    function onSelectModeChanged(~, ~)
        state.isSelecting = logical(get(state.controls.selectButton, "Value"));
        if state.isSelecting
            setStatus("selecting ambient points");
            logMessage("Point-selection mode enabled. Click inside the ambient plot to add or replace points.");
        else
            setStatus("idle");
            logMessage("Point-selection mode disabled.");
        end
    end

    function onUndoPoint(~, ~)
        if isempty(state.profilePoints)
            setStatus("nothing to undo");
            logMessage("Undo ignored because no ambient profile points are available.");
            return;
        end

        state.profilePoints(end, :) = [];
        state.profileSource = "manual";
        state.currentProfileName = "Custom";
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();

        if isempty(state.profilePoints)
            setStatus("profile cleared");
            logMessage("Removed the last point. No ambient profile points remain.");
        else
            setStatus("removed last point");
            logMessage("Removed the most recently stored ambient profile point.");
        end
    end

    function onClearProfile(~, ~)
        state.profilePoints = zeros(0, 2);
        state.profileSource = "manual";
        state.currentProfileName = "Custom";
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("profile cleared");
        logMessage("Cleared the ambient profile and previous simulation results.");
    end

    function onRunSimulation(~, ~)
        try
            params = readSimulationParameters();
            ambientProfile = buildAmbientProfile();
            results = simulateControllers(ambientProfile, params);
        catch exception
            setStatus("simulation blocked");
            logMessage(exception.message);
            return;
        end

        state.lastResults = results;
        refreshResultsPlot();
        updateMetricsBox();

        setStatus("simulation complete");
        if results.thermostatEnabled && results.pidEnabled
            logMessage(sprintf( ...
                "Simulation complete for %s. Thermostat avg %.1f degF, PID avg %.1f degF (%s mode).", ...
                ambientProfile.name, results.thermostatAverageIndoor, results.pidAverageIndoor, results.pidModeLabel));
        elseif results.thermostatEnabled
            logMessage(sprintf( ...
                "Simulation complete for %s. Thermostat avg %.1f degF.", ...
                ambientProfile.name, results.thermostatAverageIndoor));
        else
            logMessage(sprintf( ...
                "Simulation complete for %s. PID avg %.1f degF (%s mode).", ...
                ambientProfile.name, results.pidAverageIndoor, results.pidModeLabel));
        end
    end

    function onFigureClick(~, ~)
        if ~state.isSelecting || ~ishandle(state.fig)
            return;
        end

        clickedObject = hittest(state.fig);
        clickedAxes = ancestor(clickedObject, "axes");
        if isempty(clickedAxes) || clickedAxes ~= state.ambientAxes
            return;
        end

        currentPoint = get(state.ambientAxes, "CurrentPoint");
        xPoint = currentPoint(1, 1);
        yPoint = currentPoint(1, 2);
        xLimits = get(state.ambientAxes, "XLim");
        yLimits = get(state.ambientAxes, "YLim");

        if xPoint < xLimits(1) || xPoint > xLimits(2) || yPoint < yLimits(1) || yPoint > yLimits(2)
            return;
        end

        xPoint = min(max(xPoint, 0), 24);
        state.profilePoints = appendOrReplacePoint(state.profilePoints, [xPoint yPoint]);
        state.profileSource = "manual";
        state.currentProfileName = "Custom";
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("manual profile updated");
        logMessage(sprintf("Stored ambient point at t = %.2f hr, T = %.1f degF.", xPoint, yPoint));
    end

    function onCloseFigure(~, ~)
        if ishandle(state.fig)
            delete(state.fig);
        end
    end

    function points = appendOrReplacePoint(points, newPoint)
        if isempty(points)
            points = newPoint;
            return;
        end

        timeTolerance = 0.15;
        [closestDistance, closestIndex] = min(abs(points(:, 1) - newPoint(1)));
        if closestDistance <= timeTolerance
            points(closestIndex, :) = newPoint;
        else
            points(end + 1, :) = newPoint;
        end
    end

    function params = readSimulationParameters()
        params = struct();
        params.enableThermostat = logical(get(state.controls.thermostatEnabled, "Value"));
        params.enablePid = logical(get(state.controls.pidEnabled, "Value"));
        params.setpoint = readScalarField(state.controls.setpoint, "Setpoint");
        params.deadband = readScalarField(state.controls.deadband, "Deadband");
        params.initialIndoor = readScalarField(state.controls.initialIndoor, "Initial indoor temperature");
        params.roomResponseRate = readScalarField(state.controls.roomRate, "Room response rate");
        params.coolingStrength = readScalarField(state.controls.coolingStrength, "AC cooling strength");
        params.pidKp = readScalarField(state.controls.pidKp, "Kp");
        params.pidKi = readScalarField(state.controls.pidKi, "Ki");
        params.pidKd = readScalarField(state.controls.pidKd, "Kd");
        params.pidModeIndex = get(state.controls.pidMode, "Value");
        params.pidModeLabel = getSelectedPopupString(state.controls.pidMode);

        if ~params.enableThermostat && ~params.enablePid
            error("Enable at least one controller before running the simulation.");
        end

        if params.deadband <= 0
            error("Deadband must be positive.");
        end

        if params.roomResponseRate <= 0
            error("Room response rate must be positive.");
        end

        if params.coolingStrength <= 0
            error("AC cooling strength must be positive.");
        end

        if params.pidKp < 0 || params.pidKi < 0 || params.pidKd < 0
            error("Kp, Ki, and Kd must be zero or positive.");
        end
    end

    function numericValue = readScalarField(controlHandle, fieldLabel)
        numericValue = str2double(get(controlHandle, "String"));
        if ~isfinite(numericValue)
            error("%s must be a valid numeric value.", fieldLabel);
        end
    end

    function selectedString = getSelectedPopupString(controlHandle)
        optionList = get(controlHandle, "String");
        selectedIndex = get(controlHandle, "Value");
        if ischar(optionList)
            selectedString = optionList;
        else
            selectedString = optionList{selectedIndex};
        end
    end

    function profile = buildAmbientProfile()
        if isempty(state.profilePoints)
            error("Create an ambient profile by loading an example or adding at least two points.");
        end

        [pointTimes, pointTemps] = sanitizeProfilePoints(state.profilePoints);
        if numel(pointTimes) < 2
            error("At least two unique time points are required to define an ambient profile.");
        end

        if pointTimes(1) > 0
            pointTimes = [0; pointTimes];
            pointTemps = [pointTemps(1); pointTemps];
        end

        if pointTimes(end) < 24
            pointTimes = [pointTimes; 24];
            pointTemps = [pointTemps; pointTemps(end)];
        end

        ambientTemperature = interp1(pointTimes, pointTemps, state.timeHours, "pchip");

        profile = struct();
        profile.timeHours = state.timeHours;
        profile.temperature = ambientTemperature(:).';
        profile.controlTimes = pointTimes;
        profile.controlTemps = pointTemps;
        profile.name = char(state.currentProfileName);
        profile.source = char(state.profileSource);
    end

    function [pointTimes, pointTemps] = sanitizeProfilePoints(rawPoints)
        sortedPoints = sortrows(rawPoints, 1);
        sortedTimes = sortedPoints(:, 1);
        sortedTemps = sortedPoints(:, 2);
        [pointTimes, uniqueIndices] = unique(sortedTimes, "last");
        pointTemps = sortedTemps(uniqueIndices);
    end

    function results = simulateControllers(ambientProfile, params)
        timeHours = ambientProfile.timeHours;
        dtHours = timeHours(2) - timeHours(1);
        pointCount = numel(timeHours);

        thermostatTemperature = nan(size(timeHours));
        thermostatState = nan(size(timeHours));
        pidTemperature = nan(size(timeHours));
        pidCoolingLevel = nan(size(timeHours));

        if params.enableThermostat
            thermostatTemperature(:) = 0;
            thermostatState(:) = 0;
            thermostatTemperature(1) = params.initialIndoor;
            thermostatControllerState = struct("acOn", false);
        else
            thermostatControllerState = struct("acOn", false);
        end

        if params.enablePid
            pidTemperature(:) = 0;
            pidCoolingLevel(:) = 0;
            pidTemperature(1) = params.initialIndoor;
            pidControllerState = struct( ...
                "integralError", 0, ...
                "previousError", pidTemperature(1) - params.setpoint, ...
                "currentStage", 0);
        else
            pidControllerState = struct("integralError", 0, "previousError", 0, "currentStage", 0);
        end

        for index = 1:(pointCount - 1)
            if params.enableThermostat
                [thermostatCommand, thermostatControllerState] = updateThermostatControl( ...
                    thermostatControllerState, thermostatTemperature(index), params);
                thermostatState(index) = thermostatCommand;

                thermostatSlope = params.roomResponseRate * ...
                    (ambientProfile.temperature(index) - thermostatTemperature(index)) - ...
                    params.coolingStrength * thermostatCommand;

                thermostatTemperature(index + 1) = thermostatTemperature(index) + dtHours * thermostatSlope;
            end

            if params.enablePid
                [pidOutputLevel, pidControllerState] = updatePidControl( ...
                    pidControllerState, pidTemperature(index), params, dtHours);
                pidCoolingLevel(index) = pidOutputLevel;

                pidSlope = params.roomResponseRate * ...
                    (ambientProfile.temperature(index) - pidTemperature(index)) - ...
                    params.coolingStrength * pidOutputLevel;

                pidTemperature(index + 1) = pidTemperature(index) + dtHours * pidSlope;
            end
        end

        if params.enableThermostat
            [thermostatCommand, thermostatControllerState] = updateThermostatControl( ...
                thermostatControllerState, thermostatTemperature(end), params);
            thermostatState(end) = thermostatCommand;
        end

        if params.enablePid
            [pidOutputLevel, pidControllerState] = updatePidControl( ...
                pidControllerState, pidTemperature(end), params, dtHours);
            pidCoolingLevel(end) = pidOutputLevel;
        end

        results = struct();
        results.timeHours = timeHours;
        results.ambientTemperature = ambientProfile.temperature;
        results.setpoint = params.setpoint * ones(size(timeHours));
        results.thermostatEnabled = params.enableThermostat;
        results.pidEnabled = params.enablePid;
        results.pidModeLabel = params.pidModeLabel;
        results.thermostatTemperature = thermostatTemperature;
        results.thermostatState = thermostatState;
        results.pidTemperature = pidTemperature;
        results.pidCoolingLevel = pidCoolingLevel;
        results.thermostatOnTimeHours = computeControllerMetric(params.enableThermostat, sum(thermostatState) * dtHours);
        results.pidActiveHours = computeControllerMetric(params.enablePid, sum(pidCoolingLevel > 0) * dtHours);
        results.pidEquivalentHours = computeControllerMetric(params.enablePid, sum(pidCoolingLevel) * dtHours);
        results.thermostatDutyCycle = computeControllerMetric(params.enableThermostat, 100 * mean(thermostatState));
        results.pidDutyCycle = computeControllerMetric(params.enablePid, 100 * mean(pidCoolingLevel));
        results.thermostatAverageIndoor = computeControllerMetric(params.enableThermostat, mean(thermostatTemperature));
        results.pidAverageIndoor = computeControllerMetric(params.enablePid, mean(pidTemperature));
        results.profileName = ambientProfile.name;
    end

    function [acCommand, controllerState] = updateThermostatControl(controllerState, indoorTemperature, params)
        upperThreshold = params.setpoint + 0.5 * params.deadband;
        lowerThreshold = params.setpoint - 0.5 * params.deadband;

        if indoorTemperature >= upperThreshold
            controllerState.acOn = true;
        elseif indoorTemperature <= lowerThreshold
            controllerState.acOn = false;
        end

        acCommand = double(controllerState.acOn);
    end

    function [coolingLevel, controllerState] = updatePidControl(controllerState, indoorTemperature, params, dtHours)
        errorSignal = indoorTemperature - params.setpoint;
        candidateIntegral = controllerState.integralError + errorSignal * dtHours;
        derivativeError = (errorSignal - controllerState.previousError) / dtHours;

        rawDemand = ...
            params.pidKp * errorSignal + ...
            params.pidKi * candidateIntegral + ...
            params.pidKd * derivativeError;

        if params.pidModeIndex == 1
            coolingLevel = min(max(rawDemand, 0), 1);

            if (coolingLevel == 0 && errorSignal < 0) || (coolingLevel == 1 && errorSignal > 0)
                % Hold the integral term when the continuous output is saturated
                % in the same direction as the current error.
            else
                controllerState.integralError = candidateIntegral;
                rawDemand = ...
                    params.pidKp * errorSignal + ...
                    params.pidKi * controllerState.integralError + ...
                    params.pidKd * derivativeError;
                coolingLevel = min(max(rawDemand, 0), 1);
            end
        else
            controllerState.integralError = candidateIntegral;
            continuousDemand = min(max(rawDemand, 0), 1);
            stage1OnThreshold = 0.12;
            stage1OffThreshold = 0.05;
            stage2OnThreshold = 0.60;
            stage2OffThreshold = 0.40;

            switch controllerState.currentStage
                case 2
                    if continuousDemand <= stage2OffThreshold
                        if continuousDemand <= stage1OffThreshold
                            controllerState.currentStage = 0;
                        else
                            controllerState.currentStage = 1;
                        end
                    end

                case 1
                    if continuousDemand >= stage2OnThreshold
                        controllerState.currentStage = 2;
                    elseif continuousDemand <= stage1OffThreshold
                        controllerState.currentStage = 0;
                    end

                otherwise
                    if continuousDemand >= stage2OnThreshold
                        controllerState.currentStage = 2;
                    elseif continuousDemand >= stage1OnThreshold
                        controllerState.currentStage = 1;
                    else
                        controllerState.currentStage = 0;
                    end
            end

            if controllerState.currentStage == 2
                coolingLevel = 1.0;
            elseif controllerState.currentStage == 1
                coolingLevel = 0.5;
            else
                coolingLevel = 0.0;
            end
        end

        controllerState.previousError = errorSignal;
    end

    function refreshAmbientPlot()
        cla(state.ambientAxes);
        hold(state.ambientAxes, "on");
        grid(state.ambientAxes, "on");
        xlim(state.ambientAxes, [0 24]);

        if isempty(state.profilePoints)
            ylim(state.ambientAxes, [60 110]);
            title(state.ambientAxes, "Ambient Temperature Profile");
            text( ...
                state.ambientAxes, 12, 85, ...
                {"Load a profile or click points", "to create a custom ambient curve."}, ...
                "HorizontalAlignment", "center", ...
                "FontSize", 11, ...
                "Color", [0.25 0.25 0.25]);
            hold(state.ambientAxes, "off");
            return;
        end

        try
            ambientProfile = buildAmbientProfile();
            lineHandle = plot( ...
                state.ambientAxes, ambientProfile.timeHours, ambientProfile.temperature, ...
                "LineWidth", 2.1, ...
                "Color", state.colors.outdoor);

            pointHandle = scatter( ...
                state.ambientAxes, ambientProfile.controlTimes, ambientProfile.controlTemps, ...
                50, ...
                "filled", ...
                "MarkerFaceColor", [0.85 0.33 0.10], ...
                "MarkerEdgeColor", [0.20 0.20 0.20]);

            ylim(state.ambientAxes, computeTemperatureLimits(ambientProfile.controlTemps));
            title(state.ambientAxes, sprintf("Ambient Temperature Profile: %s", state.currentProfileName));
            legend(state.ambientAxes, [lineHandle pointHandle], {"Interpolated Profile", "Control Points"}, ...
                "Location", "northwest");
        catch
            sortedPoints = sortrows(state.profilePoints, 1);
            plot( ...
                state.ambientAxes, sortedPoints(:, 1), sortedPoints(:, 2), ...
                "o--", ...
                "LineWidth", 1.4, ...
                "Color", state.colors.outdoor, ...
                "MarkerFaceColor", [0.85 0.33 0.10]);
            ylim(state.ambientAxes, computeTemperatureLimits(sortedPoints(:, 2)));
            title(state.ambientAxes, "Ambient Temperature Profile");
        end

        xlabel(state.ambientAxes, "Time (hours)");
        ylabel(state.ambientAxes, "Ambient Temperature (degF)");
        hold(state.ambientAxes, "off");
    end

    function refreshResultsPlot()
        cla(state.resultsAxes);
        axes(state.resultsAxes);
        yyaxis(state.resultsAxes, "left");
        grid(state.resultsAxes, "on");

        if isempty(state.lastResults)
            title(state.resultsAxes, "Controller Comparison");
            xlabel(state.resultsAxes, "Time (hours)");
            ylabel(state.resultsAxes, "Temperature (degF)");
            set(state.resultsAxes, "YColor", state.colors.indoor);
            xlim(state.resultsAxes, [0 24]);
            ylim(state.resultsAxes, [60 100]);
            yyaxis(state.resultsAxes, "right");
            ylabel(state.resultsAxes, "Cooling Level");
            set(state.resultsAxes, "YColor", state.colors.acState);
            ylim(state.resultsAxes, [-0.05 1.05]);
            yticks(state.resultsAxes, [0 0.5 1]);
            yticklabels(state.resultsAxes, {"0%", "50%", "100%"});
            yyaxis(state.resultsAxes, "left");
            set(state.resultsAxes, "YColor", state.colors.indoor);
            text( ...
                state.resultsAxes, 12, 80, ...
                {"Run the simulation to compare", "thermostat and PID responses."}, ...
                "HorizontalAlignment", "center", ...
                "FontSize", 11, ...
                "Color", [0.25 0.25 0.25]);
            return;
        end

        axes(state.resultsAxes);
        yyaxis(state.resultsAxes, "left");
        outdoorHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 1.8, ...
            "Color", state.colors.outdoor);
        hold(state.resultsAxes, "on");
        thermostatTempHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 2.0, ...
            "Color", state.colors.indoor);
        pidTempHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-", ...
            "LineWidth", 2.0, ...
            "Color", state.colors.indoor);
        setpointHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            ":", ...
            "LineWidth", 1.5, ...
            "Color", [0.35 0.35 0.35]);
        ylabel(state.resultsAxes, "Temperature (degF)");
        set(state.resultsAxes, "YColor", state.colors.indoor);
        ylim(state.resultsAxes, computeTemperatureLimits( ...
            [state.lastResults.ambientTemperature(:); ...
             state.lastResults.thermostatTemperature(:); ...
             state.lastResults.pidTemperature(:); ...
             state.lastResults.setpoint(:)]));

        yyaxis(state.resultsAxes, "right");
        thermostatControlHandle = stairs( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 1.5, ...
            "Color", state.colors.acState);
        pidControlHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-", ...
            "LineWidth", 1.6, ...
            "Color", state.colors.acState);
        ylabel(state.resultsAxes, "Cooling Level");
        set(state.resultsAxes, "YColor", state.colors.acState);
        ylim(state.resultsAxes, [-0.05 1.05]);
        yticks(state.resultsAxes, [0 0.5 1]);
        yticklabels(state.resultsAxes, {"0%", "50%", "100%"});

        xlim(state.resultsAxes, [0 24]);
        xlabel(state.resultsAxes, "Time (hours)");
        title(state.resultsAxes, sprintf("Controller Comparison: %s", state.lastResults.profileName));

        if ~state.lastResults.thermostatEnabled
            set(thermostatTempHandle, "Visible", "off");
            set(thermostatControlHandle, "Visible", "off");
        end

        if ~state.lastResults.pidEnabled
            set(pidTempHandle, "Visible", "off");
            set(pidControlHandle, "Visible", "off");
        end

        [legendHandles, legendLabels] = buildResultLegend( ...
            outdoorHandle, thermostatTempHandle, pidTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle);
        legend(state.resultsAxes, legendHandles, legendLabels, "Location", "northwest");
        grid(state.resultsAxes, "on");

        if get(state.controls.animateCheckbox, "Value")
            animateResultsPlot( ...
                outdoorHandle, thermostatTempHandle, pidTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle);
        else
            set(outdoorHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.ambientTemperature);
            set(thermostatTempHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.thermostatTemperature);
            set(pidTempHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.pidTemperature);
            set(setpointHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.setpoint);
            set(thermostatControlHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.thermostatState);
            set(pidControlHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.pidCoolingLevel);
        end

        hold(state.resultsAxes, "off");
    end

    function updateMetricsBox()
        if isempty(state.lastResults)
            set(state.controls.thermostatStatsBox, "String", getEmptyThermostatStatsText());
            set(state.controls.pidStatsBox, "String", getEmptyPidStatsText());
            return;
        end

        if state.lastResults.thermostatEnabled
            thermostatLines = { ...
                sprintf("Thermostat Runtime: %.2f hr", state.lastResults.thermostatOnTimeHours); ...
                sprintf("Thermostat Duty: %.0f %%", state.lastResults.thermostatDutyCycle); ...
                sprintf("Thermostat Avg Temp: %.1f degF", state.lastResults.thermostatAverageIndoor)};
        else
            thermostatLines = {"Thermostat: Off"};
        end

        if state.lastResults.pidEnabled
            if strcmp(state.lastResults.pidModeLabel, "Duty Cycle")
                pidRuntimeLabel = "PID Eqv Runtime";
                pidRuntimeValue = state.lastResults.pidEquivalentHours;
            else
                pidRuntimeLabel = "PID Active Runtime";
                pidRuntimeValue = state.lastResults.pidActiveHours;
            end

            pidLines = { ...
                sprintf("PID Mode: %s", state.lastResults.pidModeLabel); ...
                sprintf("%s: %.2f hr", pidRuntimeLabel, pidRuntimeValue); ...
                sprintf("PID Duty: %.0f %%", state.lastResults.pidDutyCycle); ...
                sprintf("PID Avg Temp: %.1f degF", state.lastResults.pidAverageIndoor)};
        else
            pidLines = {"PID: Off"};
        end

        set(state.controls.thermostatStatsBox, "String", thermostatLines);
        set(state.controls.pidStatsBox, "String", pidLines);
    end

    function animateResultsPlot(outdoorHandle, thermostatTempHandle, pidTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle)
        totalPoints = numel(state.lastResults.timeHours);
        frameCount = min(totalPoints, 60);
        frameIndices = unique(round(linspace(1, totalPoints, frameCount)));
        pauseTime = 3 / max(numel(frameIndices), 1);

        for frameIndex = 1:numel(frameIndices)
            pointIndex = frameIndices(frameIndex);

            set(outdoorHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.ambientTemperature(1:pointIndex));
            set(thermostatTempHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.thermostatTemperature(1:pointIndex));
            set(pidTempHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.pidTemperature(1:pointIndex));
            set(setpointHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.setpoint(1:pointIndex));
            set(thermostatControlHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.thermostatState(1:pointIndex));
            set(pidControlHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.pidCoolingLevel(1:pointIndex));

            drawnow;
            pause(pauseTime);
        end
    end

    function limits = computeTemperatureLimits(values)
        values = values(:);
        values = values(isfinite(values));
        if isempty(values)
            limits = [60 100];
            return;
        end

        valueRange = max(values) - min(values);
        margin = max(4, 0.15 * max(valueRange, 1));
        limits = [min(values) - margin, max(values) + margin];
    end

    function emptyText = getEmptyThermostatStatsText()
        emptyText = { ...
            "Thermostat Runtime: -- hr", ...
            "Thermostat Duty: -- %", ...
            "Thermostat Avg Temp: -- degF"};
    end

    function emptyText = getEmptyPidStatsText()
        emptyText = { ...
            "PID Mode: --", ...
            "PID Eqv Runtime: -- hr", ...
            "PID Duty: -- %", ...
            "PID Avg Temp: -- degF"};
    end

    function metricValue = computeControllerMetric(isEnabled, rawValue)
        if isEnabled
            metricValue = rawValue;
        else
            metricValue = NaN;
        end
    end

    function [legendHandles, legendLabels] = buildResultLegend(outdoorHandle, thermostatTempHandle, pidTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle)
        legendHandles = outdoorHandle;
        legendLabels = {"Outdoor"};

        if state.lastResults.thermostatEnabled
            legendHandles(end + 1) = thermostatTempHandle;
            legendLabels{end + 1} = "Thermostat Indoor";
        end

        if state.lastResults.pidEnabled
            legendHandles(end + 1) = pidTempHandle;
            legendLabels{end + 1} = "PID Indoor";
        end

        legendHandles(end + 1) = setpointHandle;
        legendLabels{end + 1} = "Setpoint";

        if state.lastResults.thermostatEnabled
            legendHandles(end + 1) = thermostatControlHandle;
            legendLabels{end + 1} = "Thermostat AC";
        end

        if state.lastResults.pidEnabled
            legendHandles(end + 1) = pidControlHandle;
            legendLabels{end + 1} = "PID Cooling";
        end
    end

    function setStatus(statusText)
        set(state.controls.statusLabel, "String", sprintf("Status: %s", statusText));
    end

    function logMessage(messageText)
        if isfield(state, "controls") && isfield(state.controls, "statusLabel") && ishandle(state.controls.statusLabel)
            set(state.controls.statusLabel, "TooltipString", char(messageText));
        end
    end

    function styleAxes(axisHandle)
        set(axisHandle, ...
            "FontSize", 10, ...
            "LineWidth", 0.9, ...
            "XColor", [0 0 0], ...
            "YColor", [0 0 0], ...
            "Color", [1 1 1]);
    end

    function exampleLibrary = getExampleLibrary()
        exampleLibrary(1).name = "Summer Warm-Up";
        exampleLibrary(1).points = [ ...
            0 72; ...
            4 70; ...
            8 74; ...
            12 88; ...
            15 101; ...
            18 95; ...
            21 84; ...
            24 76];

        exampleLibrary(2).name = "Heat-Wave Spike";
        exampleLibrary(2).points = [ ...
            0 75; ...
            5 73; ...
            9 78; ...
            12 98; ...
            13.5 108; ...
            15 96; ...
            18 88; ...
            21 82; ...
            24 78];

        exampleLibrary(3).name = "Day-Night Cycle";
        exampleLibrary(3).points = [ ...
            0 69; ...
            3 66; ...
            6 64; ...
            10 72; ...
            14 83; ...
            17 89; ...
            20 80; ...
            24 70];
    end

    function colors = getPlotColors()
        colors = struct();
        colors.outdoor = [0.82 0.38 0.14];
        colors.indoor = [0.11 0.56 0.34];
        colors.acState = [0.00 0.47 0.74];
    end
end
