function hvac_pid_nn_control_demo
% HVAC control teaching demo with thermostat, PID, and NN comparison.
% The app lets users define an outdoor temperature profile, then compares
% three cooling controllers on the same room model:
% 1. A basic hysteresis thermostat
% 2. A PID controller
% 3. A neural-network controller trained to imitate PID duty-cycle output

state = struct();
state.timeHours = 0:(1 / 12):24;  % 5-minute step over one day.
state.profilePoints = zeros(0, 2);
state.profileSource = 'manual';
state.currentProfileName = 'Custom';
state.lastResults = [];
state.isSelecting = false;
state.exampleLibrary = getExampleLibrary();
state.colors = getPlotColors();
state.nnModel = createEmptyNnModel();

buildUi();
attachCallbacks();
loadExampleProfile(1);
refreshNnPanel();
setStatus("idle");
logMessage("App ready. Load an example, train the NN if needed, or sketch a custom ambient profile.");

    function buildUi()
        figColor = [0.95 0.96 0.98];
        panelColor = [0.92 0.93 0.96];

        state.fig = figure( ...
            "Name", "HVAC PID / Neural Network Control Demo", ...
            "NumberTitle", "off", ...
            "Color", figColor, ...
            "MenuBar", "none", ...
            "ToolBar", "none", ...
            "DefaultUicontrolForegroundColor", [0 0 0], ...
            "DefaultAxesXColor", [0 0 0], ...
            "DefaultAxesYColor", [0 0 0], ...
            "DefaultTextColor", [0 0 0], ...
            "Position", [40 40 1600 860], ...
            "WindowButtonDownFcn", @onFigureClick, ...
            "CloseRequestFcn", @onCloseFigure);

        state.controlsPanel = uipanel( ...
            "Parent", state.fig, ...
            "Title", "Controls", ...
            "FontSize", 11, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "Position", [0.015 0.03 0.22 0.94]);

        state.ambientAxes = axes( ...
            "Parent", state.fig, ...
            "Units", "normalized", ...
            "Position", [0.26 0.12 0.24 0.80], ...
            "Box", "on");
        title(state.ambientAxes, "Ambient Temperature Profile");
        xlabel(state.ambientAxes, "Time (hours)");
        ylabel(state.ambientAxes, "Ambient Temperature (degF)");
        grid(state.ambientAxes, "on");
        styleAxes(state.ambientAxes);

        state.resultsAxes = axes( ...
            "Parent", state.fig, ...
            "Units", "normalized", ...
            "Position", [0.53 0.12 0.24 0.80], ...
            "Box", "on");
        title(state.resultsAxes, "Controller Comparison");
        xlabel(state.resultsAxes, "Time (hours)");
        ylabel(state.resultsAxes, "Temperature (degF)");
        grid(state.resultsAxes, "on");
        styleAxes(state.resultsAxes);

        state.nnPanel = uipanel( ...
            "Parent", state.fig, ...
            "Title", "NN Controls", ...
            "FontSize", 11, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "Position", [0.80 0.03 0.185 0.94]);

        y = 0.93;
        dy = 0.041;
        editHeight = 0.036;
        labelHeight = 0.024;
        leftX = 0.05;
        editX = 0.62;
        editW = 0.27;

        state.controls.exampleMenu = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "popupmenu", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.58 editHeight], ...
            "String", {state.exampleLibrary.name}, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", "Select a built-in ambient temperature profile.");

        state.controls.loadExampleButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.66 y 0.22 editHeight], ...
            "String", "Load", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Load the selected example profile into the ambient plot.", ...
            "Callback", @onLoadExample);
        y = y - (dy + 0.006);

        state.controls.selectButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "togglebutton", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.34 editHeight], ...
            "String", "Select Points", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Enable point-selection mode, then click in the ambient axes to create a custom profile.", ...
            "Callback", @onSelectModeChanged);

        state.controls.undoButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.42 y 0.19 editHeight], ...
            "String", "Undo", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Remove the most recently stored profile point.", ...
            "Callback", @onUndoPoint);

        state.controls.clearButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.64 y 0.20 editHeight], ...
            "String", "Clear", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Clear the ambient profile and the current simulation results.", ...
            "Callback", @onClearProfile);
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.84 0.045], ...
            "String", "Room Model", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);
        y = y - 0.055;

        state.controls.initialIndoor = createLabeledEdit( ...
            state.controlsPanel, "Initial Indoor (degF)", "76", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Indoor temperature at the beginning of the simulation.");
        y = y - (dy + 0.004);

        state.controls.roomRate = createLabeledEdit( ...
            state.controlsPanel, "Room Response (1/hr)", "0.20", y, leftX, editX, editW, labelHeight, editHeight, ...
            "How strongly the room temperature drifts toward the ambient temperature.");
        y = y - (dy + 0.004);

        state.controls.coolingStrength = createLabeledEdit( ...
            state.controlsPanel, "AC Cooling (degF/hr)", "4.0", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Maximum cooling power applied when the controller command is 1.");
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.50 0.045], ...
            "String", "Basic Thermostat", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.thermostatEnabled = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.58 y 0.30 0.04], ...
            "String", "Enable", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Enable or disable the basic thermostat controller.");
        y = y - 0.055;

        state.controls.setpoint = createLabeledEdit( ...
            state.controlsPanel, "Setpoint (degF)", "74", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Shared target temperature used by all controllers.");
        y = y - (dy + 0.004);

        state.controls.deadband = createLabeledEdit( ...
            state.controlsPanel, "Deadband (degF)", "3.0", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Thermostat hysteresis width. Larger values reduce switching chatter.");
        y = y - (dy + 0.014);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.50 0.045], ...
            "String", "PID Controls", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidEnabled = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.58 y 0.30 0.04], ...
            "String", "Enable", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Enable or disable the PID controller.");
        y = y - 0.055;

        state.controls.pidKp = createLabeledEdit( ...
            state.controlsPanel, "Kp", "0.55", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Proportional gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        state.controls.pidKi = createLabeledEdit( ...
            state.controlsPanel, "Ki", "0.10", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Integral gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        state.controls.pidKd = createLabeledEdit( ...
            state.controlsPanel, "Kd", "0.02", y, leftX, editX, editW, labelHeight, editHeight, ...
            "Derivative gain for the cooling-only PID controller.");
        y = y - (dy + 0.004);

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [leftX y + 0.010 0.52 labelHeight], ...
            "String", "PID Mode", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidMode = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "popupmenu", ...
            "Units", "normalized", ...
            "Position", [editX y editW editHeight], ...
            "String", {'Duty Cycle', 'Two Stage'}, ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", "Choose continuous PWM-like cooling or two-stage cooling.");
        y = y - 0.060;

        state.controls.simulateButton = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.05 y 0.36 0.05], ...
            "String", "Run Simulation", ...
            "FontWeight", "bold", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Run all enabled controllers on the current ambient profile.", ...
            "Callback", @onRunSimulation);

        state.controls.animateCheckbox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.45 y 0.42 0.05], ...
            "String", "Animate Plot", ...
            "Value", 1, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Animate the right-side comparison plot over 3 seconds after each simulation.");

        uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.170 0.84 0.028], ...
            "String", "Run Statistics", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.thermostatStatsBox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.080 0.39 0.082], ...
            "String", getEmptyThermostatStatsText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.3, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.pidStatsBox = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.49 0.080 0.39 0.082], ...
            "String", getEmptyPidStatsText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.3, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.statusLabel = uicontrol( ...
            "Parent", state.controlsPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.05 0.020 0.85 0.026], ...
            "String", "Status: idle", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        nnY = 0.92;
        nnDy = 0.046;
        nnEditHeight = 0.038;
        nnLabelHeight = 0.026;
        nnLeftX = 0.08;
        nnEditX = 0.64;
        nnEditW = 0.22;

        state.controls.nnEnabled = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.34 0.04], ...
            "String", "Enable", ...
            "Value", 0, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Enable or disable the neural-network controller.");

        state.controls.trainNnButton = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "pushbutton", ...
            "Units", "normalized", ...
            "Position", [0.50 nnY - 0.003 0.36 0.043], ...
            "String", "Train NN", ...
            "FontWeight", "bold", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", [0.8 0.8 0.8], ...
            "TooltipString", "Train the neural-network controller using PID duty-cycle targets.", ...
            "Callback", @onTrainNn);
        nnY = nnY - (nnDy + 0.010);

        uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.84 0.035], ...
            "String", "NN Features", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);
        nnY = nnY - 0.046;

        state.controls.nnUseError = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.78 0.04], ...
            "String", "Temp Error (required)", ...
            "Value", 1, ...
            "Enable", "off", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);
        nnY = nnY - nnDy;

        state.controls.nnUseAmbient = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.68 0.04], ...
            "String", "Ambient Temp", ...
            "Value", 0, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Add outdoor temperature as an NN input feature.");
        nnY = nnY - nnDy;

        state.controls.nnUseTrend = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "checkbox", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.68 0.04], ...
            "String", "Error Trend", ...
            "Value", 0, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor, ...
            "TooltipString", "Add error trend as an NN input feature.");
        nnY = nnY - (nnDy + 0.008);

        uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 nnY 0.84 0.035], ...
            "String", "Training Settings", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);
        nnY = nnY - 0.052;

        state.controls.nnHiddenNeurons = createLabeledEdit( ...
            state.nnPanel, "Hidden Neurons", "8", nnY, nnLeftX, nnEditX, nnEditW, nnLabelHeight, nnEditHeight, ...
            "Number of neurons in the hidden layer.");
        nnY = nnY - nnDy;

        state.controls.nnLearningRate = createLabeledEdit( ...
            state.nnPanel, "Learning Rate", "0.03", nnY, nnLeftX, nnEditX, nnEditW, nnLabelHeight, nnEditHeight, ...
            "Batch-gradient-descent learning rate.");
        nnY = nnY - nnDy;

        state.controls.nnEpochs = createLabeledEdit( ...
            state.nnPanel, "Epochs", "300", nnY, nnLeftX, nnEditX, nnEditW, nnLabelHeight, nnEditHeight, ...
            "Number of training passes through the PID-imitation dataset.");

        uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 0.42 0.84 0.035], ...
            "String", "Training Summary", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.nnSummaryBox = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 0.275 0.82 0.14], ...
            "String", getEmptyNnSummaryText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.6, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 0.205 0.84 0.035], ...
            "String", "NN Run Statistics", ...
            "FontWeight", "bold", ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.nnStatsBox = uicontrol( ...
            "Parent", state.nnPanel, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.08 0.075 0.82 0.12], ...
            "String", getEmptyNnStatsText(), ...
            "HorizontalAlignment", "left", ...
            "FontSize", 8.6, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", panelColor);

        state.controls.footerLabel = uicontrol( ...
            "Parent", state.fig, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [0.61 0.01 0.36 0.025], ...
            "String", "Prof. Jon Komperda, University of Illinois Chicago, 2026", ...
            "HorizontalAlignment", "right", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", figColor);

        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
    end

    function editHandle = createLabeledEdit(parentHandle, labelText, defaultValue, yPos, lx, ex, ew, lh, eh, tooltipText)
        backgroundColor = get(parentHandle, "BackgroundColor");
        uicontrol( ...
            "Parent", parentHandle, ...
            "Style", "text", ...
            "Units", "normalized", ...
            "Position", [lx yPos + 0.010 0.52 lh], ...
            "String", labelText, ...
            "HorizontalAlignment", "left", ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", backgroundColor);

        editHandle = uicontrol( ...
            "Parent", parentHandle, ...
            "Style", "edit", ...
            "Units", "normalized", ...
            "Position", [ex yPos ew eh], ...
            "String", defaultValue, ...
            "ForegroundColor", [0 0 0], ...
            "BackgroundColor", "white", ...
            "TooltipString", tooltipText);
    end

    function attachCallbacks()
        set(state.controls.setpoint, "Callback", @(~, ~) onNnTeacherSettingChanged("Setpoint changed. The NN model may be out of date."));
        set(state.controls.initialIndoor, "Callback", @(~, ~) onNnTeacherSettingChanged("Initial indoor temperature changed. The NN model may be out of date."));
        set(state.controls.roomRate, "Callback", @(~, ~) onNnTeacherSettingChanged("Room response changed. The NN model may be out of date."));
        set(state.controls.coolingStrength, "Callback", @(~, ~) onNnTeacherSettingChanged("Cooling strength changed. The NN model may be out of date."));
        set(state.controls.pidKp, "Callback", @(~, ~) onNnTeacherSettingChanged("PID gains changed. The NN model may be out of date."));
        set(state.controls.pidKi, "Callback", @(~, ~) onNnTeacherSettingChanged("PID gains changed. The NN model may be out of date."));
        set(state.controls.pidKd, "Callback", @(~, ~) onNnTeacherSettingChanged("PID gains changed. The NN model may be out of date."));

        set(state.controls.nnUseAmbient, "Callback", @(~, ~) onNnFeatureSelectionChanged("NN feature selection changed. Retraining is recommended."));
        set(state.controls.nnUseTrend, "Callback", @(~, ~) onNnFeatureSelectionChanged("NN feature selection changed. Retraining is recommended."));
        set(state.controls.nnHiddenNeurons, "Callback", @(~, ~) onNnHyperparameterChanged("NN hidden neurons changed. Retraining is recommended."));
        set(state.controls.nnLearningRate, "Callback", @(~, ~) onNnHyperparameterChanged("NN learning rate changed. Retraining is recommended."));
        set(state.controls.nnEpochs, "Callback", @(~, ~) onNnHyperparameterChanged("NN epochs changed. Retraining is recommended."));
    end

    function onLoadExample(~, ~)
        loadExampleProfile(get(state.controls.exampleMenu, "Value"));
    end

    function loadExampleProfile(exampleIndex)
        exampleProfile = state.exampleLibrary(exampleIndex);
        state.profilePoints = exampleProfile.points;
        state.profileSource = 'example';
        state.currentProfileName = exampleProfile.name;
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("loaded example");
        logMessage(sprintf("Loaded ambient profile: %s.", exampleProfile.name));
    end

    function onSelectModeChanged(~, ~)
        state.isSelecting = logical(get(state.controls.selectButton, "Value"));
        if state.isSelecting
            setStatus("selecting ambient points");
            logMessage("Point-selection mode enabled. Click inside the ambient plot to add or replace points.");
        else
            setStatus("idle");
            logMessage("Point-selection mode disabled.");
        end
    end

    function onUndoPoint(~, ~)
        if isempty(state.profilePoints)
            setStatus("nothing to undo");
            logMessage("Undo ignored because no ambient profile points are available.");
            return;
        end

        state.profilePoints(end, :) = [];
        state.profileSource = 'manual';
        state.currentProfileName = 'Custom';
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();

        if isempty(state.profilePoints)
            setStatus("profile cleared");
            logMessage("Removed the last point. No ambient profile points remain.");
        else
            setStatus("removed last point");
            logMessage("Removed the most recently stored ambient profile point.");
        end
    end

    function onClearProfile(~, ~)
        state.profilePoints = zeros(0, 2);
        state.profileSource = 'manual';
        state.currentProfileName = 'Custom';
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("profile cleared");
        logMessage("Cleared the ambient profile and previous simulation results.");
    end

    function onRunSimulation(~, ~)
        try
            params = readAppParameters(true, true);
            ambientProfile = buildAmbientProfile();
            results = simulateControllers(ambientProfile, params);
        catch exception
            setStatus("simulation blocked");
            logMessage(exception.message);
            return;
        end

        state.lastResults = results;
        refreshResultsPlot();
        updateMetricsBox();
        refreshNnPanel();

        setStatus("simulation complete");
        try
            summaryMessage = buildSimulationSummary(results);
        catch
            summaryMessage = sprintf('Simulation complete for %s.', char(results.profileName));
        end
        logMessage(summaryMessage);
    end

    function onTrainNn(~, ~)
        try
            setStatus("training nn");
            drawnow;

            params = readAppParameters(false, false);
            trainingSettings = readNnTrainingSettings();
            featureFlags = readNnFeatureFlagsFromUi();
            trainingProfiles = getTrainingProfiles();
            [trainingInputs, trainingTargets] = buildNnTrainingDataset(trainingProfiles, params, featureFlags);
            state.nnModel = trainNeuralNetwork(trainingInputs, trainingTargets, featureFlags, trainingSettings);

            refreshNnPanel();
            setStatus("nn trained");
            logMessage(sprintf( ...
                "NN training complete. Final loss %.5f using %s.", ...
                state.nnModel.loss, char(state.nnModel.featureSummary)));
        catch exception
            refreshNnPanel();
            setStatus("nn training blocked");
            logMessage(exception.message);
        end
    end

    function onFigureClick(~, ~)
        if ~state.isSelecting || ~ishandle(state.fig)
            return;
        end

        clickedObject = hittest(state.fig);
        clickedAxes = ancestor(clickedObject, "axes");
        if isempty(clickedAxes) || clickedAxes ~= state.ambientAxes
            return;
        end

        currentPoint = get(state.ambientAxes, "CurrentPoint");
        xPoint = currentPoint(1, 1);
        yPoint = currentPoint(1, 2);
        xLimits = get(state.ambientAxes, "XLim");
        yLimits = get(state.ambientAxes, "YLim");

        if xPoint < xLimits(1) || xPoint > xLimits(2) || yPoint < yLimits(1) || yPoint > yLimits(2)
            return;
        end

        xPoint = min(max(xPoint, 0), 24);
        state.profilePoints = appendOrReplacePoint(state.profilePoints, [xPoint yPoint]);
        state.profileSource = 'manual';
        state.currentProfileName = 'Custom';
        state.lastResults = [];
        refreshAmbientPlot();
        refreshResultsPlot();
        updateMetricsBox();
        setStatus("manual profile updated");
        logMessage(sprintf("Stored ambient point at t = %.2f hr, T = %.1f degF.", xPoint, yPoint));
    end

    function onCloseFigure(~, ~)
        if ishandle(state.fig)
            delete(state.fig);
        end
    end

    function onNnFeatureSelectionChanged(messageText)
        markNnModelStale(messageText);
        refreshNnPanel();
    end

    function onNnHyperparameterChanged(messageText)
        markNnModelStale(messageText);
        refreshNnPanel();
    end

    function onNnTeacherSettingChanged(messageText)
        markNnModelStale(messageText);
        refreshNnPanel();
    end

    function points = appendOrReplacePoint(points, newPoint)
        if isempty(points)
            points = newPoint;
            return;
        end

        timeTolerance = 0.15;
        [closestDistance, closestIndex] = min(abs(points(:, 1) - newPoint(1)));
        if closestDistance <= timeTolerance
            points(closestIndex, :) = newPoint;
        else
            points(end + 1, :) = newPoint;
        end
    end

    function params = readAppParameters(requireEnabledController, requireTrainedNn)
        params = struct();
        params.enableThermostat = logical(get(state.controls.thermostatEnabled, "Value"));
        params.enablePid = logical(get(state.controls.pidEnabled, "Value"));
        params.enableNn = logical(get(state.controls.nnEnabled, "Value"));
        params.setpoint = readScalarField(state.controls.setpoint, "Setpoint");
        params.deadband = readScalarField(state.controls.deadband, "Deadband");
        params.initialIndoor = readScalarField(state.controls.initialIndoor, "Initial indoor temperature");
        params.roomResponseRate = readScalarField(state.controls.roomRate, "Room response rate");
        params.coolingStrength = readScalarField(state.controls.coolingStrength, "AC cooling strength");
        params.pidKp = readScalarField(state.controls.pidKp, "Kp");
        params.pidKi = readScalarField(state.controls.pidKi, "Ki");
        params.pidKd = readScalarField(state.controls.pidKd, "Kd");
        params.pidModeIndex = get(state.controls.pidMode, "Value");
        params.pidModeLabel = getSelectedPopupString(state.controls.pidMode);

        if requireEnabledController && ~params.enableThermostat && ~params.enablePid && ~params.enableNn
            error("Enable at least one controller before running the simulation.");
        end

        if params.enableNn && requireTrainedNn && ~state.nnModel.isReady
            error("Train the NN controller before enabling it for simulation.");
        end

        if params.deadband <= 0
            error("Deadband must be positive.");
        end

        if params.roomResponseRate <= 0
            error("Room response rate must be positive.");
        end

        if params.coolingStrength <= 0
            error("AC cooling strength must be positive.");
        end

        if params.pidKp < 0 || params.pidKi < 0 || params.pidKd < 0
            error("Kp, Ki, and Kd must be zero or positive.");
        end
    end

    function settings = readNnTrainingSettings()
        settings = struct();
        settings.hiddenNeurons = readScalarField(state.controls.nnHiddenNeurons, "Hidden neurons");
        settings.learningRate = readScalarField(state.controls.nnLearningRate, "Learning rate");
        settings.epochs = readScalarField(state.controls.nnEpochs, "Epochs");

        if settings.hiddenNeurons < 1 || abs(settings.hiddenNeurons - round(settings.hiddenNeurons)) > 1e-9
            error("Hidden neurons must be a positive integer.");
        end

        if settings.learningRate <= 0
            error("Learning rate must be positive.");
        end

        if settings.epochs < 1 || abs(settings.epochs - round(settings.epochs)) > 1e-9
            error("Epochs must be a positive integer.");
        end

        settings.hiddenNeurons = round(settings.hiddenNeurons);
        settings.epochs = round(settings.epochs);
    end

    function numericValue = readScalarField(controlHandle, fieldLabel)
        numericValue = str2double(get(controlHandle, "String"));
        if ~isfinite(numericValue)
            error("%s must be a valid numeric value.", fieldLabel);
        end
    end

    function selectedString = getSelectedPopupString(controlHandle)
        optionList = get(controlHandle, "String");
        selectedIndex = get(controlHandle, "Value");
        if ischar(optionList)
            selectedString = optionList;
        else
            selectedString = optionList{selectedIndex};
        end
    end

    function featureFlags = readNnFeatureFlagsFromUi()
        featureFlags = struct();
        featureFlags.useError = true;
        featureFlags.useAmbient = logical(get(state.controls.nnUseAmbient, "Value"));
        featureFlags.useTrend = logical(get(state.controls.nnUseTrend, "Value"));
    end

    function summaryText = getFeatureSummary(featureFlags)
        featureNames = {'Temp Error'};
        if featureFlags.useAmbient
            featureNames{end + 1} = 'Ambient Temp';
        end
        if featureFlags.useTrend
            featureNames{end + 1} = 'Error Trend';
        end
        summaryText = joinTextParts(featureNames, ', ');
    end

    function profile = buildAmbientProfile()
        profile = buildAmbientProfileFromPoints(state.profilePoints, char(state.currentProfileName), char(state.profileSource));
    end

    function profile = buildAmbientProfileFromPoints(rawPoints, profileName, profileSource)
        if isempty(rawPoints)
            error("Create an ambient profile by loading an example or adding at least two points.");
        end

        [pointTimes, pointTemps] = sanitizeProfilePoints(rawPoints);
        if numel(pointTimes) < 2
            error("At least two unique time points are required to define an ambient profile.");
        end

        if pointTimes(1) > 0
            pointTimes = [0; pointTimes];
            pointTemps = [pointTemps(1); pointTemps];
        end

        if pointTimes(end) < 24
            pointTimes = [pointTimes; 24];
            pointTemps = [pointTemps; pointTemps(end)];
        end

        ambientTemperature = interp1(pointTimes, pointTemps, state.timeHours, "pchip");

        profile = struct();
        profile.timeHours = state.timeHours;
        profile.temperature = ambientTemperature(:).';
        profile.controlTimes = pointTimes;
        profile.controlTemps = pointTemps;
        profile.name = profileName;
        profile.source = profileSource;
    end

    function [pointTimes, pointTemps] = sanitizeProfilePoints(rawPoints)
        sortedPoints = sortrows(rawPoints, 1);
        sortedTimes = sortedPoints(:, 1);
        sortedTemps = sortedPoints(:, 2);
        [pointTimes, uniqueIndices] = unique(sortedTimes, "last");
        pointTemps = sortedTemps(uniqueIndices);
    end

    function trainingProfiles = getTrainingProfiles()
        trainingProfiles = repmat(struct( ...
            "timeHours", state.timeHours, ...
            "temperature", zeros(size(state.timeHours)), ...
            "controlTimes", [], ...
            "controlTemps", [], ...
            "name", "", ...
            "source", ""), 1, numel(state.exampleLibrary));

        for profileIndex = 1:numel(state.exampleLibrary)
            exampleProfile = state.exampleLibrary(profileIndex);
            trainingProfiles(profileIndex) = buildAmbientProfileFromPoints( ...
                exampleProfile.points, exampleProfile.name, "example");
        end

        try
            currentProfile = buildAmbientProfile();
            trainingProfiles(end + 1) = currentProfile;
        catch
            % Keep the built-in library only if the current profile is incomplete.
        end
    end

    function [trainingInputs, trainingTargets] = buildNnTrainingDataset(trainingProfiles, params, featureFlags)
        trainingInputs = [];
        trainingTargets = [];

        for profileIndex = 1:numel(trainingProfiles)
            [profileInputs, profileTargets] = collectPidImitationData(trainingProfiles(profileIndex), params, featureFlags);
            trainingInputs = [trainingInputs; profileInputs]; %#ok<AGROW>
            trainingTargets = [trainingTargets; profileTargets]; %#ok<AGROW>
        end

        if isempty(trainingInputs)
            error("The NN training dataset is empty. Load or define an ambient profile first.");
        end
    end

    function [sampleInputs, sampleTargets] = collectPidImitationData(ambientProfile, params, featureFlags)
        timeHours = ambientProfile.timeHours;
        dtHours = timeHours(2) - timeHours(1);
        pointCount = numel(timeHours);
        indoorTemperature = zeros(pointCount, 1);
        indoorTemperature(1) = params.initialIndoor;
        controllerState = struct( ...
            "integralError", 0, ...
            "previousError", indoorTemperature(1) - params.setpoint, ...
            "currentStage", 0);

        sampleInputs = zeros(pointCount, countEnabledFeatures(featureFlags));
        sampleTargets = zeros(pointCount, 1);

        teacherParams = params;
        teacherParams.pidModeIndex = 1;
        teacherParams.pidModeLabel = 'Duty Cycle';

        for index = 1:(pointCount - 1)
            sampleInputs(index, :) = buildNnFeatureRow( ...
                indoorTemperature(index), ambientProfile.temperature(index), params.setpoint, ...
                controllerState.previousError, dtHours, featureFlags);

            [pidCoolingLevel, controllerState] = updatePidControl( ...
                controllerState, indoorTemperature(index), teacherParams, dtHours);
            sampleTargets(index) = pidCoolingLevel;

            indoorSlope = params.roomResponseRate * ...
                (ambientProfile.temperature(index) - indoorTemperature(index)) - ...
                params.coolingStrength * pidCoolingLevel;
            indoorTemperature(index + 1) = indoorTemperature(index) + dtHours * indoorSlope;
        end

        sampleInputs(end, :) = buildNnFeatureRow( ...
            indoorTemperature(end), ambientProfile.temperature(end), params.setpoint, ...
            controllerState.previousError, dtHours, featureFlags);
        [sampleTargets(end), controllerState] = updatePidControl( ...
            controllerState, indoorTemperature(end), teacherParams, dtHours); %#ok<NASGU>
    end

    function featureCount = countEnabledFeatures(featureFlags)
        featureCount = 1 + double(featureFlags.useAmbient) + double(featureFlags.useTrend);
    end

    function results = simulateControllers(ambientProfile, params)
        timeHours = ambientProfile.timeHours;
        dtHours = timeHours(2) - timeHours(1);
        pointCount = numel(timeHours);

        thermostatTemperature = nan(size(timeHours));
        thermostatState = nan(size(timeHours));
        pidTemperature = nan(size(timeHours));
        pidCoolingLevel = nan(size(timeHours));
        nnTemperature = nan(size(timeHours));
        nnCoolingLevel = nan(size(timeHours));

        if params.enableThermostat
            thermostatTemperature(:) = 0;
            thermostatState(:) = 0;
            thermostatTemperature(1) = params.initialIndoor;
            thermostatControllerState = struct("acOn", false);
        else
            thermostatControllerState = struct("acOn", false);
        end

        if params.enablePid
            pidTemperature(:) = 0;
            pidCoolingLevel(:) = 0;
            pidTemperature(1) = params.initialIndoor;
            pidControllerState = struct( ...
                "integralError", 0, ...
                "previousError", pidTemperature(1) - params.setpoint, ...
                "currentStage", 0);
        else
            pidControllerState = struct("integralError", 0, "previousError", 0, "currentStage", 0);
        end

        if params.enableNn
            nnTemperature(:) = 0;
            nnCoolingLevel(:) = 0;
            nnTemperature(1) = params.initialIndoor;
            nnControllerState = struct("previousError", nnTemperature(1) - params.setpoint);
            nnModel = state.nnModel;
        else
            nnControllerState = struct("previousError", 0);
            nnModel = createEmptyNnModel();
        end

        for index = 1:(pointCount - 1)
            ambientTemperature = ambientProfile.temperature(index);

            if params.enableThermostat
                [thermostatCommand, thermostatControllerState] = updateThermostatControl( ...
                    thermostatControllerState, thermostatTemperature(index), params);
                thermostatState(index) = thermostatCommand;

                thermostatSlope = params.roomResponseRate * ...
                    (ambientTemperature - thermostatTemperature(index)) - ...
                    params.coolingStrength * thermostatCommand;
                thermostatTemperature(index + 1) = thermostatTemperature(index) + dtHours * thermostatSlope;
            end

            if params.enablePid
                [pidOutputLevel, pidControllerState] = updatePidControl( ...
                    pidControllerState, pidTemperature(index), params, dtHours);
                pidCoolingLevel(index) = pidOutputLevel;

                pidSlope = params.roomResponseRate * ...
                    (ambientTemperature - pidTemperature(index)) - ...
                    params.coolingStrength * pidOutputLevel;
                pidTemperature(index + 1) = pidTemperature(index) + dtHours * pidSlope;
            end

            if params.enableNn
                [nnOutputLevel, nnControllerState] = updateNnControl( ...
                    nnControllerState, nnTemperature(index), ambientTemperature, params.setpoint, nnModel, dtHours);
                nnCoolingLevel(index) = nnOutputLevel;

                nnSlope = params.roomResponseRate * ...
                    (ambientTemperature - nnTemperature(index)) - ...
                    params.coolingStrength * nnOutputLevel;
                nnTemperature(index + 1) = nnTemperature(index) + dtHours * nnSlope;
            end
        end

        if params.enableThermostat
            [thermostatCommand, thermostatControllerState] = updateThermostatControl( ...
                thermostatControllerState, thermostatTemperature(end), params); %#ok<NASGU>
            thermostatState(end) = thermostatCommand;
        end

        if params.enablePid
            [pidOutputLevel, pidControllerState] = updatePidControl( ...
                pidControllerState, pidTemperature(end), params, dtHours); %#ok<NASGU>
            pidCoolingLevel(end) = pidOutputLevel;
        end

        if params.enableNn
            [nnOutputLevel, nnControllerState] = updateNnControl( ...
                nnControllerState, nnTemperature(end), ambientProfile.temperature(end), params.setpoint, nnModel, dtHours); %#ok<NASGU>
            nnCoolingLevel(end) = nnOutputLevel;
        end

        results = struct();
        results.timeHours = timeHours;
        results.ambientTemperature = ambientProfile.temperature;
        results.setpoint = params.setpoint * ones(size(timeHours));
        results.thermostatEnabled = params.enableThermostat;
        results.pidEnabled = params.enablePid;
        results.nnEnabled = params.enableNn;
        results.pidModeLabel = params.pidModeLabel;
        results.thermostatTemperature = thermostatTemperature;
        results.thermostatState = thermostatState;
        results.pidTemperature = pidTemperature;
        results.pidCoolingLevel = pidCoolingLevel;
        results.nnTemperature = nnTemperature;
        results.nnCoolingLevel = nnCoolingLevel;
        results.thermostatOnTimeHours = computeControllerMetric(params.enableThermostat, sum(thermostatState) * dtHours);
        results.pidActiveHours = computeControllerMetric(params.enablePid, sum(pidCoolingLevel > 0) * dtHours);
        results.pidEquivalentHours = computeControllerMetric(params.enablePid, sum(pidCoolingLevel) * dtHours);
        results.nnEquivalentHours = computeControllerMetric(params.enableNn, sum(nnCoolingLevel) * dtHours);
        results.thermostatDutyCycle = computeControllerMetric(params.enableThermostat, 100 * mean(thermostatState));
        results.pidDutyCycle = computeControllerMetric(params.enablePid, 100 * mean(pidCoolingLevel));
        results.nnDutyCycle = computeControllerMetric(params.enableNn, 100 * mean(nnCoolingLevel));
        results.thermostatAverageIndoor = computeControllerMetric(params.enableThermostat, mean(thermostatTemperature));
        results.pidAverageIndoor = computeControllerMetric(params.enablePid, mean(pidTemperature));
        results.nnAverageIndoor = computeControllerMetric(params.enableNn, mean(nnTemperature));
        results.nnTrainingLoss = computeControllerMetric(params.enableNn, state.nnModel.loss);
        results.nnIsStale = params.enableNn && state.nnModel.isStale;
        results.nnFeatureSummary = char(state.nnModel.featureSummary);
        results.profileName = ambientProfile.name;
    end

    function [acCommand, controllerState] = updateThermostatControl(controllerState, indoorTemperature, params)
        upperThreshold = params.setpoint + 0.5 * params.deadband;
        lowerThreshold = params.setpoint - 0.5 * params.deadband;

        if indoorTemperature >= upperThreshold
            controllerState.acOn = true;
        elseif indoorTemperature <= lowerThreshold
            controllerState.acOn = false;
        end

        acCommand = double(controllerState.acOn);
    end

    function [coolingLevel, controllerState] = updatePidControl(controllerState, indoorTemperature, params, dtHours)
        errorSignal = indoorTemperature - params.setpoint;
        candidateIntegral = controllerState.integralError + errorSignal * dtHours;
        derivativeError = (errorSignal - controllerState.previousError) / dtHours;

        rawDemand = ...
            params.pidKp * errorSignal + ...
            params.pidKi * candidateIntegral + ...
            params.pidKd * derivativeError;

        if params.pidModeIndex == 1
            coolingLevel = min(max(rawDemand, 0), 1);

            if (coolingLevel == 0 && errorSignal < 0) || (coolingLevel == 1 && errorSignal > 0)
                % Hold the integral term when the continuous output is saturated
                % in the same direction as the current error.
            else
                controllerState.integralError = candidateIntegral;
                rawDemand = ...
                    params.pidKp * errorSignal + ...
                    params.pidKi * controllerState.integralError + ...
                    params.pidKd * derivativeError;
                coolingLevel = min(max(rawDemand, 0), 1);
            end
        else
            controllerState.integralError = candidateIntegral;
            continuousDemand = min(max(rawDemand, 0), 1);
            stage1OnThreshold = 0.12;
            stage1OffThreshold = 0.05;
            stage2OnThreshold = 0.60;
            stage2OffThreshold = 0.40;

            switch controllerState.currentStage
                case 2
                    if continuousDemand <= stage2OffThreshold
                        if continuousDemand <= stage1OffThreshold
                            controllerState.currentStage = 0;
                        else
                            controllerState.currentStage = 1;
                        end
                    end

                case 1
                    if continuousDemand >= stage2OnThreshold
                        controllerState.currentStage = 2;
                    elseif continuousDemand <= stage1OffThreshold
                        controllerState.currentStage = 0;
                    end

                otherwise
                    if continuousDemand >= stage2OnThreshold
                        controllerState.currentStage = 2;
                    elseif continuousDemand >= stage1OnThreshold
                        controllerState.currentStage = 1;
                    else
                        controllerState.currentStage = 0;
                    end
            end

            if controllerState.currentStage == 2
                coolingLevel = 1.0;
            elseif controllerState.currentStage == 1
                coolingLevel = 0.5;
            else
                coolingLevel = 0.0;
            end
        end

        controllerState.previousError = errorSignal;
    end

    function [coolingLevel, controllerState] = updateNnControl(controllerState, indoorTemperature, ambientTemperature, setpoint, nnModel, dtHours)
        featureRow = buildNnFeatureRow( ...
            indoorTemperature, ambientTemperature, setpoint, controllerState.previousError, dtHours, nnModel.featureFlags);
        coolingLevel = inferNnCoolingLevel(nnModel, featureRow);
        controllerState.previousError = indoorTemperature - setpoint;
    end

    function featureRow = buildNnFeatureRow(indoorTemperature, ambientTemperature, setpoint, previousError, dtHours, featureFlags)
        errorSignal = indoorTemperature - setpoint;
        featureRow = errorSignal;

        if featureFlags.useAmbient
            featureRow(end + 1) = ambientTemperature; %#ok<AGROW>
        end

        if featureFlags.useTrend
            errorTrend = (errorSignal - previousError) / dtHours;
            featureRow(end + 1) = errorTrend; %#ok<AGROW>
        end
    end

    function coolingLevel = inferNnCoolingLevel(nnModel, featureRow)
        normalizedFeature = (featureRow(:).' - nnModel.inputMean) ./ nnModel.inputScale;
        hiddenVector = tanh(nnModel.W1 * normalizedFeature(:) + nnModel.b1);
        outputValue = sigmoid(nnModel.W2 * hiddenVector + nnModel.b2);
        coolingLevel = min(max(outputValue, 0), 1);
        coolingLevel = double(coolingLevel);
    end

    function nnModel = trainNeuralNetwork(trainingInputs, trainingTargets, featureFlags, trainingSettings)
        sampleCount = size(trainingInputs, 1);
        inputCount = size(trainingInputs, 2);

        inputMean = mean(trainingInputs, 1);
        inputScale = std(trainingInputs, 0, 1);
        inputScale(inputScale < 1e-8) = 1;
        normalizedInputs = (trainingInputs - inputMean) ./ inputScale;
        targets = trainingTargets(:);

        savedRng = rng;
        cleanupRng = onCleanup(@() rng(savedRng)); %#ok<NASGU>
        rng(7, "twister");

        hiddenCount = trainingSettings.hiddenNeurons;
        W1 = 0.25 * randn(hiddenCount, inputCount);
        b1 = zeros(hiddenCount, 1);
        W2 = 0.25 * randn(1, hiddenCount);
        b2 = 0;

        finalLoss = NaN;
        learningRate = trainingSettings.learningRate;

        for epoch = 1:trainingSettings.epochs
            hiddenState = tanh(normalizedInputs * W1.' + ones(sampleCount, 1) * b1.');
            outputState = sigmoid(hiddenState * W2.' + b2);

            outputError = outputState - targets;
            finalLoss = mean(outputError .^ 2);

            delta2 = (2 / sampleCount) * outputError .* outputState .* (1 - outputState);
            gradW2 = delta2.' * hiddenState;
            gradb2 = sum(delta2, 1);

            delta1 = (delta2 * W2) .* (1 - hiddenState .^ 2);
            gradW1 = delta1.' * normalizedInputs;
            gradb1 = sum(delta1, 1).';

            W1 = W1 - learningRate * gradW1;
            b1 = b1 - learningRate * gradb1;
            W2 = W2 - learningRate * gradW2;
            b2 = b2 - learningRate * gradb2;
        end

        nnModel = struct();
        nnModel.isReady = true;
        nnModel.isStale = false;
        nnModel.loss = finalLoss;
        nnModel.W1 = W1;
        nnModel.b1 = b1;
        nnModel.W2 = W2;
        nnModel.b2 = b2;
        nnModel.inputMean = inputMean;
        nnModel.inputScale = inputScale;
        nnModel.featureFlags = featureFlags;
        nnModel.featureSummary = getFeatureSummary(featureFlags);
        nnModel.teacherLabel = 'PID Duty Cycle';
        nnModel.hiddenNeurons = trainingSettings.hiddenNeurons;
        nnModel.learningRate = trainingSettings.learningRate;
        nnModel.epochs = trainingSettings.epochs;
    end

    function outputValue = sigmoid(inputValue)
        inputValue = max(min(inputValue, 40), -40);
        outputValue = 1 ./ (1 + exp(-inputValue));
    end

    function refreshAmbientPlot()
        cla(state.ambientAxes);
        hold(state.ambientAxes, "on");
        grid(state.ambientAxes, "on");
        xlim(state.ambientAxes, [0 24]);

        if isempty(state.profilePoints)
            ylim(state.ambientAxes, [60 110]);
            title(state.ambientAxes, "Ambient Temperature Profile");
            text( ...
                state.ambientAxes, 12, 85, ...
                {'Load a profile or click points', 'to create a custom ambient curve.'}, ...
                "HorizontalAlignment", "center", ...
                "FontSize", 11, ...
                "Color", [0.25 0.25 0.25]);
            hold(state.ambientAxes, "off");
            return;
        end

        try
            ambientProfile = buildAmbientProfile();
            lineHandle = plot( ...
                state.ambientAxes, ambientProfile.timeHours, ambientProfile.temperature, ...
                "LineWidth", 2.1, ...
                "Color", state.colors.outdoor);

            pointHandle = scatter( ...
                state.ambientAxes, ambientProfile.controlTimes, ambientProfile.controlTemps, ...
                50, ...
                "filled", ...
                "MarkerFaceColor", [0.85 0.33 0.10], ...
                "MarkerEdgeColor", [0.20 0.20 0.20]);

            ylim(state.ambientAxes, computeTemperatureLimits(ambientProfile.controlTemps));
            title(state.ambientAxes, sprintf("Ambient Temperature Profile: %s", state.currentProfileName));
            legend(state.ambientAxes, [lineHandle pointHandle], {'Interpolated Profile', 'Control Points'}, ...
                "Location", "northwest");
        catch
            sortedPoints = sortrows(state.profilePoints, 1);
            plot( ...
                state.ambientAxes, sortedPoints(:, 1), sortedPoints(:, 2), ...
                "o--", ...
                "LineWidth", 1.4, ...
                "Color", state.colors.outdoor, ...
                "MarkerFaceColor", [0.85 0.33 0.10]);
            ylim(state.ambientAxes, computeTemperatureLimits(sortedPoints(:, 2)));
            title(state.ambientAxes, "Ambient Temperature Profile");
        end

        xlabel(state.ambientAxes, "Time (hours)");
        ylabel(state.ambientAxes, "Ambient Temperature (degF)");
        hold(state.ambientAxes, "off");
    end

    function refreshResultsPlot()
        cla(state.resultsAxes);
        axes(state.resultsAxes);
        yyaxis(state.resultsAxes, "left");
        grid(state.resultsAxes, "on");

        if isempty(state.lastResults)
            title(state.resultsAxes, "Controller Comparison");
            xlabel(state.resultsAxes, "Time (hours)");
            ylabel(state.resultsAxes, "Temperature (degF)");
            set(state.resultsAxes, "YColor", state.colors.indoor);
            xlim(state.resultsAxes, [0 24]);
            ylim(state.resultsAxes, [60 100]);
            yyaxis(state.resultsAxes, "right");
            ylabel(state.resultsAxes, "Cooling Level");
            set(state.resultsAxes, "YColor", state.colors.acState);
            ylim(state.resultsAxes, [-0.05 1.05]);
            yticks(state.resultsAxes, [0 0.5 1]);
            yticklabels(state.resultsAxes, {'0%', '50%', '100%'});
            yyaxis(state.resultsAxes, "left");
            set(state.resultsAxes, "YColor", state.colors.indoor);
            text( ...
                state.resultsAxes, 12, 80, ...
                {'Run the simulation to compare', 'thermostat, PID, and NN responses.'}, ...
                "HorizontalAlignment", "center", ...
                "FontSize", 11, ...
                "Color", [0.25 0.25 0.25]);
            return;
        end

        yyaxis(state.resultsAxes, "left");
        outdoorHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 1.8, ...
            "Color", state.colors.outdoor);
        hold(state.resultsAxes, "on");
        thermostatTempHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 2.0, ...
            "Color", state.colors.indoor);
        pidTempHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-", ...
            "LineWidth", 2.0, ...
            "Color", state.colors.indoor);
        nnTempHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-.", ...
            "LineWidth", 2.0, ...
            "Color", state.colors.indoor);
        setpointHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            ":", ...
            "LineWidth", 1.5, ...
            "Color", [0.35 0.35 0.35]);
        ylabel(state.resultsAxes, "Temperature (degF)");
        set(state.resultsAxes, "YColor", state.colors.indoor);
        ylim(state.resultsAxes, computeTemperatureLimits( ...
            [state.lastResults.ambientTemperature(:); ...
             state.lastResults.thermostatTemperature(:); ...
             state.lastResults.pidTemperature(:); ...
             state.lastResults.nnTemperature(:); ...
             state.lastResults.setpoint(:)]));

        yyaxis(state.resultsAxes, "right");
        thermostatControlHandle = stairs( ...
            state.resultsAxes, nan, nan, ...
            "--", ...
            "LineWidth", 1.5, ...
            "Color", state.colors.acState);
        pidControlHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-", ...
            "LineWidth", 1.6, ...
            "Color", state.colors.acState);
        nnControlHandle = plot( ...
            state.resultsAxes, nan, nan, ...
            "-.", ...
            "LineWidth", 1.6, ...
            "Color", state.colors.acState);
        ylabel(state.resultsAxes, "Cooling Level");
        set(state.resultsAxes, "YColor", state.colors.acState);
        ylim(state.resultsAxes, [-0.05 1.05]);
        yticks(state.resultsAxes, [0 0.5 1]);
        yticklabels(state.resultsAxes, {'0%', '50%', '100%'});

        xlim(state.resultsAxes, [0 24]);
        xlabel(state.resultsAxes, "Time (hours)");
        title(state.resultsAxes, sprintf("Controller Comparison: %s", state.lastResults.profileName));

        if ~state.lastResults.thermostatEnabled
            set(thermostatTempHandle, "Visible", "off");
            set(thermostatControlHandle, "Visible", "off");
        end

        if ~state.lastResults.pidEnabled
            set(pidTempHandle, "Visible", "off");
            set(pidControlHandle, "Visible", "off");
        end

        if ~state.lastResults.nnEnabled
            set(nnTempHandle, "Visible", "off");
            set(nnControlHandle, "Visible", "off");
        end

        [legendHandles, legendLabels] = buildResultLegend( ...
            outdoorHandle, thermostatTempHandle, pidTempHandle, nnTempHandle, ...
            setpointHandle, thermostatControlHandle, pidControlHandle, nnControlHandle);
        legend(state.resultsAxes, legendHandles, legendLabels, "Location", "northwest");
        grid(state.resultsAxes, "on");

        if get(state.controls.animateCheckbox, "Value")
            animateResultsPlot( ...
                outdoorHandle, thermostatTempHandle, pidTempHandle, nnTempHandle, ...
                setpointHandle, thermostatControlHandle, pidControlHandle, nnControlHandle);
        else
            set(outdoorHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.ambientTemperature);
            set(thermostatTempHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.thermostatTemperature);
            set(pidTempHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.pidTemperature);
            set(nnTempHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.nnTemperature);
            set(setpointHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.setpoint);
            set(thermostatControlHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.thermostatState);
            set(pidControlHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.pidCoolingLevel);
            set(nnControlHandle, ...
                "XData", state.lastResults.timeHours, ...
                "YData", state.lastResults.nnCoolingLevel);
        end

        hold(state.resultsAxes, "off");
    end

    function updateMetricsBox()
        if isempty(state.lastResults)
            set(state.controls.thermostatStatsBox, "String", getEmptyThermostatStatsText());
            set(state.controls.pidStatsBox, "String", getEmptyPidStatsText());
            refreshNnPanel();
            return;
        end

        if state.lastResults.thermostatEnabled
            thermostatLines = { ...
                sprintf("Thermo Runtime: %.2f hr", state.lastResults.thermostatOnTimeHours); ...
                sprintf("Thermo Duty: %.0f %%", state.lastResults.thermostatDutyCycle); ...
                sprintf("Thermo Avg Temp: %.1f degF", state.lastResults.thermostatAverageIndoor)};
        else
            thermostatLines = {'Thermostat: Off'};
        end

        if state.lastResults.pidEnabled
            if strcmp(char(state.lastResults.pidModeLabel), 'Duty Cycle')
                pidRuntimeLabel = 'PID Eqv Runtime';
                pidRuntimeValue = state.lastResults.pidEquivalentHours;
            else
                pidRuntimeLabel = 'PID Active Run';
                pidRuntimeValue = state.lastResults.pidActiveHours;
            end

            pidLines = { ...
                sprintf("PID Mode: %s", state.lastResults.pidModeLabel); ...
                sprintf("%s: %.2f hr", pidRuntimeLabel, pidRuntimeValue); ...
                sprintf("PID Duty: %.0f %%", state.lastResults.pidDutyCycle); ...
                sprintf("PID Avg Temp: %.1f degF", state.lastResults.pidAverageIndoor)};
        else
            pidLines = {'PID: Off'};
        end

        set(state.controls.thermostatStatsBox, "String", thermostatLines);
        set(state.controls.pidStatsBox, "String", pidLines);
        refreshNnPanel();
    end

    function refreshNnPanel()
        currentFeatureSummary = getFeatureSummary(readNnFeatureFlagsFromUi());

        if state.nnModel.isReady
            if state.nnModel.isStale
                modelStatus = 'Stale';
            else
                modelStatus = 'Ready';
            end
            trainingLossText = sprintf("%.5f", state.nnModel.loss);
            modelFeatureSummary = char(state.nnModel.featureSummary);
        else
            modelStatus = 'Untrained';
            trainingLossText = '--';
            modelFeatureSummary = currentFeatureSummary;
        end

        summaryLines = { ...
            sprintf("Training Status: %s", modelStatus); ...
            sprintf("Training Loss: %s", trainingLossText); ...
            sprintf("Model Features: %s", modelFeatureSummary); ...
            sprintf("Current Features: %s", currentFeatureSummary); ...
            'Teacher: PID Duty Cycle'};
        set(state.controls.nnSummaryBox, "String", summaryLines);

        if isempty(state.lastResults) || ~isfield(state.lastResults, "nnEnabled")
            nnLines = getEmptyNnStatsText();
        elseif state.lastResults.nnEnabled
            if state.lastResults.nnIsStale
                runtimeStatus = 'Stale';
            else
                runtimeStatus = 'Ready';
            end
            nnLines = { ...
                sprintf("NN Eqv Runtime: %.2f hr", state.lastResults.nnEquivalentHours); ...
                sprintf("NN Duty: %.0f %%", state.lastResults.nnDutyCycle); ...
                sprintf("NN Avg Temp: %.1f degF", state.lastResults.nnAverageIndoor); ...
                sprintf("Training Loss: %.5f", state.lastResults.nnTrainingLoss); ...
                sprintf("Model Status: %s", runtimeStatus)};
        else
            nnLines = { ...
                'NN: Off'; ...
                'NN Duty: -- %'; ...
                'NN Avg Temp: -- degF'; ...
                sprintf("Training Loss: %s", trainingLossText); ...
                sprintf("Model Status: %s", modelStatus)};
        end

        set(state.controls.nnStatsBox, "String", nnLines);
    end

    function animateResultsPlot(outdoorHandle, thermostatTempHandle, pidTempHandle, nnTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle, nnControlHandle)
        totalPoints = numel(state.lastResults.timeHours);
        frameCount = min(totalPoints, 60);
        frameIndices = unique(round(linspace(1, totalPoints, frameCount)));
        pauseTime = 3 / max(numel(frameIndices), 1);

        for frameIndex = 1:numel(frameIndices)
            pointIndex = frameIndices(frameIndex);

            set(outdoorHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.ambientTemperature(1:pointIndex));
            set(thermostatTempHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.thermostatTemperature(1:pointIndex));
            set(pidTempHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.pidTemperature(1:pointIndex));
            set(nnTempHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.nnTemperature(1:pointIndex));
            set(setpointHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.setpoint(1:pointIndex));
            set(thermostatControlHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.thermostatState(1:pointIndex));
            set(pidControlHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.pidCoolingLevel(1:pointIndex));
            set(nnControlHandle, ...
                "XData", state.lastResults.timeHours(1:pointIndex), ...
                "YData", state.lastResults.nnCoolingLevel(1:pointIndex));

            drawnow;
            pause(pauseTime);
        end
    end

    function limits = computeTemperatureLimits(values)
        values = values(:);
        values = values(isfinite(values));
        if isempty(values)
            limits = [60 100];
            return;
        end

        valueRange = max(values) - min(values);
        margin = max(4, 0.15 * max(valueRange, 1));
        limits = [min(values) - margin, max(values) + margin];
    end

    function emptyText = getEmptyThermostatStatsText()
        emptyText = { ...
            'Thermo Runtime: -- hr', ...
            'Thermo Duty: -- %', ...
            'Thermo Avg Temp: -- degF'};
    end

    function emptyText = getEmptyPidStatsText()
        emptyText = { ...
            'PID Mode: --', ...
            'PID Eqv Runtime: -- hr', ...
            'PID Duty: -- %', ...
            'PID Avg Temp: -- degF'};
    end

    function emptyText = getEmptyNnSummaryText()
        emptyText = { ...
            'Training Status: Untrained', ...
            'Training Loss: --', ...
            'Model Features: Temp Error', ...
            'Current Features: Temp Error', ...
            'Teacher: PID Duty Cycle'};
    end

    function emptyText = getEmptyNnStatsText()
        emptyText = { ...
            'NN Eqv Runtime: -- hr', ...
            'NN Duty: -- %', ...
            'NN Avg Temp: -- degF', ...
            'Training Loss: --', ...
            'Model Status: Untrained'};
    end

    function metricValue = computeControllerMetric(isEnabled, rawValue)
        if isEnabled
            metricValue = rawValue;
        else
            metricValue = NaN;
        end
    end

    function [legendHandles, legendLabels] = buildResultLegend(outdoorHandle, thermostatTempHandle, pidTempHandle, nnTempHandle, setpointHandle, thermostatControlHandle, pidControlHandle, nnControlHandle)
        legendHandles = outdoorHandle;
        legendLabels = {'Outdoor'};

        if state.lastResults.thermostatEnabled
            legendHandles(end + 1) = thermostatTempHandle;
            legendLabels{end + 1} = 'Thermostat Indoor';
        end

        if state.lastResults.pidEnabled
            legendHandles(end + 1) = pidTempHandle;
            legendLabels{end + 1} = 'PID Indoor';
        end

        if state.lastResults.nnEnabled
            legendHandles(end + 1) = nnTempHandle;
            legendLabels{end + 1} = 'NN Indoor';
        end

        legendHandles(end + 1) = setpointHandle;
        legendLabels{end + 1} = 'Setpoint';

        if state.lastResults.thermostatEnabled
            legendHandles(end + 1) = thermostatControlHandle;
            legendLabels{end + 1} = 'Thermostat AC';
        end

        if state.lastResults.pidEnabled
            legendHandles(end + 1) = pidControlHandle;
            legendLabels{end + 1} = 'PID Cooling';
        end

        if state.lastResults.nnEnabled
            legendHandles(end + 1) = nnControlHandle;
            legendLabels{end + 1} = 'NN Cooling';
        end
    end

    function summaryText = buildSimulationSummary(results)
        summaryParts = {};
        if results.thermostatEnabled
            summaryParts{end + 1} = sprintf('Thermostat avg %.1f degF', results.thermostatAverageIndoor); %#ok<AGROW>
        end
        if results.pidEnabled
            summaryParts{end + 1} = sprintf('PID avg %.1f degF', results.pidAverageIndoor); %#ok<AGROW>
        end
        if results.nnEnabled
            summaryParts{end + 1} = sprintf('NN avg %.1f degF', results.nnAverageIndoor); %#ok<AGROW>
        end

        if isempty(summaryParts)
            summaryText = 'Simulation completed.';
        else
            summaryText = sprintf('Simulation complete for %s. %s.', ...
                char(results.profileName), joinTextParts(summaryParts, ', '));
        end
    end

    function joinedText = joinTextParts(textParts, delimiter)
        if isempty(textParts)
            joinedText = '';
            return;
        end

        normalizedParts = cell(size(textParts));
        for partIndex = 1:numel(textParts)
            normalizedParts{partIndex} = char(textParts{partIndex});
        end

        joinedText = normalizedParts{1};
        for partIndex = 2:numel(normalizedParts)
            joinedText = [joinedText delimiter normalizedParts{partIndex}]; %#ok<AGROW>
        end
    end

    function setStatus(statusText)
        set(state.controls.statusLabel, "String", sprintf("Status: %s", statusText));
    end

    function logMessage(messageText)
        if isfield(state, "controls") && isfield(state.controls, "statusLabel") && ishandle(state.controls.statusLabel)
            set(state.controls.statusLabel, "TooltipString", char(messageText));
        end
    end

    function styleAxes(axisHandle)
        set(axisHandle, ...
            "FontSize", 10, ...
            "LineWidth", 0.9, ...
            "XColor", [0 0 0], ...
            "YColor", [0 0 0], ...
            "Color", [1 1 1]);
    end

    function markNnModelStale(messageText)
        if state.nnModel.isReady
            state.nnModel.isStale = true;
            setStatus("nn model stale");
            logMessage(messageText);
        end
    end

    function nnModel = createEmptyNnModel()
        featureFlags = struct("useError", true, "useAmbient", false, "useTrend", false);
        nnModel = struct();
        nnModel.isReady = false;
        nnModel.isStale = false;
        nnModel.loss = NaN;
        nnModel.W1 = [];
        nnModel.b1 = [];
        nnModel.W2 = [];
        nnModel.b2 = 0;
        nnModel.inputMean = [];
        nnModel.inputScale = [];
        nnModel.featureFlags = featureFlags;
        nnModel.featureSummary = 'Temp Error';
        nnModel.teacherLabel = 'PID Duty Cycle';
        nnModel.hiddenNeurons = NaN;
        nnModel.learningRate = NaN;
        nnModel.epochs = NaN;
    end

    function exampleLibrary = getExampleLibrary()
        exampleLibrary(1).name = 'Summer Warm-Up';
        exampleLibrary(1).points = [ ...
            0 72; ...
            4 70; ...
            8 74; ...
            12 88; ...
            15 101; ...
            18 95; ...
            21 84; ...
            24 76];

        exampleLibrary(2).name = 'Heat-Wave Spike';
        exampleLibrary(2).points = [ ...
            0 75; ...
            5 73; ...
            9 78; ...
            12 98; ...
            13.5 108; ...
            15 96; ...
            18 88; ...
            21 82; ...
            24 78];

        exampleLibrary(3).name = 'Day-Night Cycle';
        exampleLibrary(3).points = [ ...
            0 69; ...
            3 66; ...
            6 64; ...
            10 72; ...
            14 83; ...
            17 89; ...
            20 80; ...
            24 70];
    end

    function colors = getPlotColors()
        colors = struct();
        colors.outdoor = [0.82 0.38 0.14];
        colors.indoor = [0.11 0.56 0.34];
        colors.acState = [0.00 0.47 0.74];
    end
end
